import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import Nav from '@/components/sections/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className='"container mx-auto px-4"'>
      <body className={inter.className}>
        <Nav />
      
        {children}
      </body>
      </div>
    </html>
  )
}
